### ISSUE TITLE
IP over IP

### ISSUE THREAD

**Issue by cfalcken** [telekom/5g-trace-visualizer#1]
In case there is IP traffic sent over another IP layer, the second one is more useful as src and dst.
I found I can fix this by replacing the following:

             ip_showname = packet.find("proto[@name='ip']").attrib['showname']

with this:

             ip_showname = packet.findall("proto[@name='ip']")[-1].attrib['showname']

**Comment by jkolom** [comment]
Thanks for the contributions! I hope the scripts turned up useful for you :smile: 
I just pushed a couple of commits fixing #1, #2, #3. The Wireshark version checking is now a bit more proper and uses the packaging Python module.
We did not test with IP-in-IP (we may end up doing that at some point), so it was never tested :sweat_smile:
