### ISSUE TITLE
 [proposed label = question] Wireshark portable == is 5g-trace-visualizer for WIN only ?

### ISSUE THREAD

**Issue by slashTPA** [telekom/5g-trace-visualizer#10]
Hi,

the Readme.md states "Add in this folder the Wireshark portable installations so that they can be automatically called by the program." - am I right, assuming that this project is designed for WIN only? 
Is there any chance to invoke an installed version of **Wireshark on LX** ? 
I do have it included in the path.

(base) [tpa@devel 5g-trace-visualizer]$ **tshark --v**
TShark (Wireshark) 3.2.5 (Git commit ed20ddea8138)

(base) [tpa@devel 5g-trace-visualizer]$ **wireshark --v**
Wireshark 3.2.5 (Git commit ed20ddea8138)

Any hint welcomed. If I just try:

_**python trace_visualizer.py -wireshark "3.2.5" /.../5G-Attach.pcapng**_ 

I run into following FileNotFoundError, as the search seems to be done in "..**./wireshark/WiresharkPortable_3.2.5/App/Wireshark/tshark**'" subdir only (that does not exist in my case):

(base) [tpa@devel 5g-trace-visualizer]$ python trace_visualizer.py -wireshark "3.2.5" /home/tpa/__SNDBOX/5GC_Traces/5G-Attach.pcapng/5G-Attach.pcapng 
Searching for plantuml.jar under /home/tpa/__SNDBOX/5g-trace-visualizer/plantuml.jar
Found plantuml.jar

Platform system detected: Linux
5G Wireshark trace visualizer for 5G protocol
Input file: /home/tpa/__SNDBOX/5GC_Traces/5G-Attach.pcapng/5G-Attach.pcapng
Pods YAML file: None
Maximum messages per file: 100
Debug: None
String un-escaping for HTTP requests: True
OpenStack servers file: None
HTTP/2 headers to ignore: None
Diagrams to output: ip,k8s_pod,k8s_namespace
Simple diagrams: False
Force show frames if using simple diagrams: 
Show PFCP/GTPv2 heartbeat messages: False
Show HTTP/2 in spurious TCP retransmission messages: True
Ignore PFCP packet duplicates: True
Show timestamp in diagram: False
Show self-messages: False

Using Wireshark version 3.2.5
Wireshark supports nas-5gs.null_decipher option. Applying
Generating PDML files from PCAP to /home/tpa/__SNDBOX/5GC_Traces/5G-Attach.pcapng/5G-Attach_3.2.5.pdml
['/home/tpa/__SNDBOX/5g-trace-visualizer/wireshark/WiresharkPortable_3.2.5/App/Wireshark/tshark', '-r', '/home/tpa/__SNDBOX/5GC_Traces/5G-Attach.pcapng/5G-Attach.pcapng', '-2', '-d', 'tcp.port==32445,http2', '-d', 'tcp.port==5002,http2', '-d', 'tcp.port==5000,http2', '-d', 'tcp.port==32665,http2', '-d', 'tcp.port==80,http2', '-d', 'tcp.port==32077,http2', '-d', 'tcp.port==5006,http2', '-d', 'tcp.port==8080,http2', '-d', 'tcp.port==3000,http2', '-o', 'nas-5gs.null_decipher: TRUE', '-Y', '(http2 and (http2.type == 0 || http2.type == 1)) or ngap or nas-5gs or pfcp or gtpv2 or diameter or radius or gtpprime or icmp', '-T', 'pdml', '-J', 'http2 ngap pfcp gtpv2 tcp diameter radius gtpprime icmp', '-n']
Traceback (most recent call last):
  File "trace_visualizer.py", line 1313, in <module>
    input_file = call_wireshark(args.wireshark, input_file, args.http2ports)
  File "trace_visualizer.py", line 1137, in call_wireshark
    output_file = call_wireshark_for_one_version(wireshark_version, input_file_str, http2ports_string)
  File "trace_visualizer.py", line 1221, in call_wireshark_for_one_version
    subprocess.run(tshark_command, stdout=outfile)
  File "/home/tpa/anaconda3/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/tpa/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/tpa/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tpa/__SNDBOX/5g-trace-visualizer/wireshark/**WiresharkPortable_3.2.5/App/Wireshark/tshark'**

Thx.

**Comment by jkolom** [comment]
Hi!

I did develop this in Windows, but I do not use any Windows specifics. From what I got from #4 it should work.
In order to use the OS-installed Wireshark from your path, use ``OS`` as version.

You can see how the call to ``tshark`` is generated [here](https://github.com/telekom/5g-trace-visualizer/blob/34e2d59fa65b48efb10b3618019f4fb7328fc07c/trace_visualizer.py#L1169).

For the ``OS`` case the command will not contain a the path. The path was introduced because for the initial captures we needed Wireshark 2.9.0 for the NAS messages while for other messages we needed another version (an old NAS version was used and 2.9.0 was the last version with a dissector correctly decoding the messages).

The call in your example would look like this

``python trace_visualizer.py -wireshark "OS" /.../5G-Attach.pcapng``

Let me know if that works :smiley:

**Comment by slashTPA** [comment]
Thanks a lot for fast response.
 
Besides some "Packet XX is malformed" messages - **Now it workes like a charm.** :-D

**Comment by jkolom** [comment]
Glad that it worked :smile: 

If the packet appears as malformed in Wireshark, it will also appear like that in the diagram. The packet dissection is performed by Wireshark and exported as PDML (XML actually) :sweat_smile: 

If NAS is the issue, what you can try is to test different Wireshark versions until you find one that works. Wireshark's NAS dissectors are quite strict and most of the times once they find something unexpected they stop decoding and you get a "Malformed" tag.
