### ISSUE TITLE
Don't show Diameter heartbeats

### ISSUE THREAD

**Issue by OrlandoST** [telekom/5g-trace-visualizer#19]
Code have options `-showheartbeat`, but it dont work with diameter proto, because you use parse_gtpv2_proto() for parsing diameter_proto

I think it will be great, if this project can skip Diameter Common Application messages, when `-showheartbeat` is set.

How I create parse_diam_proto() function to parse diameter.
If you want I can create pull request

**Comment by jkolom** [comment]
Hi,

As with #18, happy to get any pull request with an improvement as I basically have no time :) Happy to see that it is useful to some :D

As I know that sharing traces is typically something a bit sensitive, I would really appreaciate if you could test it with your own traces.

The tool implemented traces "as needed" based on the output we got from internal trials, so if something is not taken into account, most probably we did not see it in a specific testing we did. The tool was only tested on a couple of 4G-5G handovers, so it surely misses many things regarding non-5GC protocols.

The reason for the lazy Diameter implementation is that I was OK with only doing a formatting of the whole payload (basically ``nas_5g_proto_to_dict`` and then formatted as YAML). The name of the function does not really imply "5G NAS" as what is read is in reality the XML structure of the PDML file.

The easiest way would be just to duplicate the ``parse_gtpv2_proto`` function and add the necessary additions to check whether the diameter payload has a heartbeat flag.

BR

**Comment by OrlandoST** [comment]
Feature added in 8c86ab3d5a32397d2752a6a2bf1df8a4d96a62dc
