### ISSUE TITLE
Multiple SCTP chunks in one packet

### ISSUE THREAD

**Issue by rtommy** [telekom/5g-trace-visualizer#27]
There are cases when a 5GC NF uses SCTP (for example AMF towards gNodeB), which means that one packet could contain more than one SCTP DATA chunk. These chunks contain NGAP messages.

The import_pdml function says:

        # For 5GC
        # Fix case (see free5GC trace) where there are several elements (not correct but well...)
        ngap_proto = packet.findall("proto[@name='ngap']")
        if len(ngap_proto) == 0:
            ngap_proto = None
        elif len(ngap_proto) == 1:
            ngap_proto = ngap_proto[0]

So this part (and perhaps more) would require an update to consider the fact of multiple SCTP chunks (meaning multiple NGAP messages) in one packet, which is entirely correct protocol behaviour.

![SCTP_multiple_chunks_in_one_packet](https://user-images.githubusercontent.com/63186686/236657115-71859480-66ad-4bad-a517-61c04737c621.PNG)

**Comment by jkolom** [comment]
It seems like the fix in #28 fixed this one. I checked by repeating a ``<proto name="ngap" showname="NG Application Protocol" [...]`` element in a PDML file and the SVG correctly displays a second NGAP PDU in the description.
Hopefully this fixes the issue :)
![image](https://user-images.githubusercontent.com/520942/236784362-cf073af6-3ef1-43f0-b38c-803771bd9192.png)

**Comment by rtommy** [comment]
yes, it's okay for me too, not sure what I missed before. it's working as expected.
