### ISSUE TITLE
I Need Help Searching for Open Source Software Stack for 3G

### ISSUE THREAD

**Issue by serttasbugrahan** [telekom/5g-trace-visualizer#35]
I am looking for open source software stack for 3G, like OpenAirInterface for 5G or Osmocom for 2G. (Osmocom has partial support for 3G)

Kindly asking you to forward me to the right source who may know.

Thank you for your time and kind attention.

Best Regards,

**Comment by jkolom** [comment]
Hi,
I would suggest to you you to ask the Open Source Wireless interface. This is only a tool to visualize traces. You mention OpenAirInterface and Osmocom. They have been around for a long time. I doubt that I know anything in this regard that they would not be able to tell you right away.
I will close this issue as off-topic.
