### ISSUE TITLE
Support docker compose

### ISSUE THREAD

**Issue by calee0219** [telekom/5g-trace-visualizer#8]
Is it possible to add feature to label host label according to docker-compose's yaml file?
The parameter might similar to k8s pod data I think?

The compose file may similar like [this](https://github.com/free5gc/free5gc-compose/blob/master/docker-compose.yaml)

https://github.com/free5gc/free5gc-compose/blob/master/docker-compose.yaml

**Comment by jkolom** [comment]
Sure, that would not be difficult to do.
I just updated the documentation with examples from the trace I got from you (many thanks for that!). As long as the yaml file contains a mapping between the assigned IP address and the pod name, that could be added.

Currently, we only support the IP mapping that we have seen (i.e. Calico), check the readme.md file for examples based on your traces ([link](https://github.com/telekom/5g-trace-visualizer/blob/master/README.md))

I did not see any IP in the file you point to. Could you check if running kubectl get pods --all-namespaces -o yaml generates one with the assigned IPs?

As long as there is a yaml file where I can get the mapping, I could add support for that. Just let me know what file I could use (that includes IP information) and I could check it.
